import { chromium } from "playwright";
const plan = { household: "single", people: [{ currentAge: 60, superBalance: 500000, salary: 90000 }], homeowner: true, home: { value: 800000, growthReal: 0 }, outsideSuper: 120000, annualOutsideSavings: 5000, retirementAge: 67, spendingMode: "flat", targetSpending: 45000, investmentReturn: 6, inflation: 2.5, lifeExpectancy: 90 };
const b = await chromium.launch();
const pg = await b.newPage({ viewport: { width: 1150, height: 720 } });
await pg.addInitScript((p) => { localStorage.setItem("au-retirement-plan", JSON.stringify(p)); localStorage.setItem("au-retirement-working-ts", String(Date.now())); }, plan);
await pg.goto("http://localhost:3000", { waitUntil: "networkidle" });
await pg.waitForTimeout(3500);
await pg.locator("section").filter({ hasText: "RETIREMENT CONFIDENCE" }).first().screenshot({ path: "e:/tmp/para.png" });
console.log("captured");
await b.close();
