// AUTO-GENERATED by scripts/gen-version.mjs on each build — do not edit by hand.
export const APP_VERSION = "1.0.376";
export const BUILD = 376;
export const GIT_SHA = "7a3dc67";
export const BUILD_DATE = "2026-07-21";
