// AUTO-GENERATED by scripts/gen-version.mjs on each build — do not edit by hand.
export const APP_VERSION = "1.0.770";
export const BUILD = 770;
export const GIT_SHA = "c5e955f";
export const BUILD_DATE = "2026-09-07";
// Newest-first; used by the deploy seed step to auto-draft a release (see autoDraftRelease).
export const COMMITS: { sha: string; subject: string }[] = [
  {
    "sha": "c5e955f",
    "subject": "Budget Quiz: restructure the play-mode modal so it fits without scrolling"
  },
  {
    "sha": "5dd713e",
    "subject": "Budget Quiz: swap the game-controller icon for a quiz icon (📝)"
  },
  {
    "sha": "514516c",
    "subject": "Budget Quiz: monthly / yearly toggle"
  },
  {
    "sha": "0404621",
    "subject": "Budget builder: rename the \"Play mode\" toggle to \"Quiz mode\""
  },
  {
    "sha": "b578938",
    "subject": "Budget vs Adjust-spending: clear-on-commit (budget is the source of truth)"
  },
  {
    "sha": "a76da15",
    "subject": "Wizard Goal step: fit without vertical scroll"
  },
  {
    "sha": "13b2f13",
    "subject": "Budget Quiz: kill the horizontal scrollbar on the play-mode modal"
  },
  {
    "sha": "bf625e7",
    "subject": "Add stale-tab reload prompt + surface the Adjust-spending lever in the budget"
  },
  {
    "sha": "abc3e46",
    "subject": "Rename the feature \"Budget Quest\" -> \"Budget Quiz\" (user-facing)"
  },
  {
    "sha": "7430606",
    "subject": "Budget Quest /budget: super becomes a slider + responsive inputs"
  },
  {
    "sha": "7a77eb8",
    "subject": "Budget Quest: obvious clickable category cards + icons, fix tier threshold"
  },
  {
    "sha": "0e2ad88",
    "subject": "Budget Quest: make play mode quiz-first with per-category zone dials"
  },
  {
    "sha": "32093fc",
    "subject": "Budget Quest quizzes: make every category a proper series (3+ questions)"
  },
  {
    "sha": "c3e10f5",
    "subject": "Budget Quest: per-category \"work it out\" quizzes"
  },
  {
    "sha": "841bdc6",
    "subject": "Budget Quest — Phase 1: gamified budget play mode (skin over the budget engine)"
  },
  {
    "sha": "434b6ca",
    "subject": "Dashboard: restore the \"Bert is running the numbers\" spinner on load"
  },
  {
    "sha": "036af73",
    "subject": "Fix: applying a new budget was masked by an active adjust-spending lever"
  },
  {
    "sha": "e847a91",
    "subject": "Age Pension calculator: always show income + add a stats card"
  },
  {
    "sha": "aaa1ed5",
    "subject": "Age Pension calculator: make assessable assets typeable (no $1.4m cap)"
  },
  {
    "sha": "7128cdd",
    "subject": "Age Pension calculator: make clear the income comes from deeming"
  },
  {
    "sha": "9621823",
    "subject": "Add standalone Age Pension calculator to /learn"
  },
  {
    "sha": "271d354",
    "subject": "Aged care calculator: add a RAD vs DAP effective-return comparison"
  },
  {
    "sha": "2ba52ad",
    "subject": "Aged care calculator: explain the three means-test constants"
  },
  {
    "sha": "d632b94",
    "subject": "Aged care: true up fee config to the 1 Jul 2026 vintage"
  },
  {
    "sha": "45efa58",
    "subject": "Aged care calculator: show the per-day workings in the fee breakdown"
  },
  {
    "sha": "b39a232",
    "subject": "Aged care calculator: itemise how assessable assets is built"
  },
  {
    "sha": "5d5e886",
    "subject": "Aged care: statutory means test (asset + income tapers) with shown workings"
  },
  {
    "sha": "3910398",
    "subject": "TTR calculator: default the slider to the sweet spot + live Step 3"
  },
  {
    "sha": "4b85770",
    "subject": "TTR calculator: sweet spot isn't always the cap — fix two solver bugs"
  },
  {
    "sha": "ed98982",
    "subject": "TTR calculator: reorganise into three clear steps"
  },
  {
    "sha": "a81da07",
    "subject": "TTR calculator: $100 slider step so it lands on the sweet spot"
  },
  {
    "sha": "f1f69e6",
    "subject": "TTR calculator: add a concessional-cap meter above the sacrifice slider"
  },
  {
    "sha": "b41d03e",
    "subject": "Add a TTR \"sweet spot\" calculator to the knowledge base"
  },
  {
    "sha": "ac67852",
    "subject": "Aged-care calculator: fix room price under DAP + explain RAD/DAP"
  },
  {
    "sha": "8b9bf99",
    "subject": "Wizard: let salary sacrifice reach the full concessional cap again"
  },
  {
    "sha": "35e7113",
    "subject": "Wizard: show remaining concessional headroom on the contributions step"
  },
  {
    "sha": "49be2e8",
    "subject": "Guided setup: refresh the average super balances to ASFA June 2023"
  },
  {
    "sha": "648837e",
    "subject": "Financial Summary: split offsets into separate per-loan assets"
  },
  {
    "sha": "2f1d5a0",
    "subject": "Financial Summary: list offset-account cash as an asset"
  },
  {
    "sha": "d9e14b5",
    "subject": "Offset accounts on investment-property loans (phase 2)"
  },
  {
    "sha": "eee8230",
    "subject": "Fix: net-worth chart opened the savings year breakdown, not net worth"
  },
  {
    "sha": "52d3c47",
    "subject": "Show the offset account in the net-worth chart (+ fix a total mismatch)"
  },
  {
    "sha": "0a5a516",
    "subject": "Home loan: compute \"Paid off by age\" (offset-aware) instead of manual entry"
  },
  {
    "sha": "b32dd89",
    "subject": "Offset accounts on the home loan (v1)"
  },
  {
    "sha": "9f78b71",
    "subject": "Fix hero flashing the previous scenario on load (deferred-value regression)"
  },
  {
    "sha": "444375e",
    "subject": "Budget: include the home loan in the benchmark \"Your budget\" total"
  },
  {
    "sha": "329f9be",
    "subject": "Budget: turn the preset picker into a benchmark once the budget is refined"
  },
  {
    "sha": "c6ccf57",
    "subject": "Budget: show the carried home-loan expense in the \"Your home\" card"
  },
  {
    "sha": "2901769",
    "subject": "Dashboard: float the status notice as an auto-dismissing toast"
  },
  {
    "sha": "d9d7d66",
    "subject": "Dashboard: move the scenario summary card above the hero"
  },
  {
    "sha": "f2fdb78",
    "subject": "Dashboard: delete the hidden \"What will it take?\" card + its dead code"
  },
  {
    "sha": "746aeac",
    "subject": "Dashboard: make quick-adjust sliders responsive (was laggy)"
  },
  {
    "sha": "8417c42",
    "subject": "Ages are whole numbers only (no fractional age entry)"
  },
  {
    "sha": "f32359b",
    "subject": "Fix chart crash on scenarios with a fractional current age + life-event pins"
  },
  {
    "sha": "5bf1f70",
    "subject": "Dashboard: hide the \"What will it take?\" goal-seek card"
  },
  {
    "sha": "59009cf",
    "subject": "Visitor tracking: stop httpOnly re-minting a new visitor id every visit"
  },
  {
    "sha": "bae56ad",
    "subject": "Copy: \"Refine scenario\" → \"Refine your scenario\" (button + guide reference)"
  },
  {
    "sha": "7af38dc",
    "subject": "Guided setup: move phase-2 inputs above the chart (no slider jump on mobile)"
  },
  {
    "sha": "9b33aa1",
    "subject": "Bert: serve poses as direct static <img> (fixes iOS home-screen loading)"
  },
  {
    "sha": "26c1246",
    "subject": "Shared view: \"Build your own free plan\" starts from a clean slate"
  },
  {
    "sha": "98dbc9c",
    "subject": "Hero loading: \"Bert is running the numbers…\""
  },
  {
    "sha": "54bc2c9",
    "subject": "Shared view: move the read-only notice into the hero, tidy the right column"
  },
  {
    "sha": "0f01a3c",
    "subject": "Shared view: drop the duplicate \"Build your own\" button from the top banner"
  },
  {
    "sha": "8ebe674",
    "subject": "Learn: add \"The aged-care illiquidity trap\" article"
  },
  {
    "sha": "0d01895",
    "subject": "Age Pension modal: itemise the assessed former home in \"What's counted\""
  },
  {
    "sha": "51e39cf",
    "subject": "Hero: fill the empty right column on shared/read-only views"
  },
  {
    "sha": "eda7cc5",
    "subject": "Hero: remove the 💡 \"spend more\" headroom nudge card"
  },
  {
    "sha": "937d9c2",
    "subject": "Bert: add the eureka pose to the Aged care cost calculator header"
  },
  {
    "sha": "6aec99d",
    "subject": "Bert: remove the clock pose (hair got clipped in the cut-out)"
  },
  {
    "sha": "9b57ebf",
    "subject": "Bert: drop the confidence-hero celebration; add him to What-If + stress test"
  },
  {
    "sha": "01b1716",
    "subject": "Bert: /learn article headers + a celebration on a bulletproof plan"
  },
  {
    "sha": "dac6c5b",
    "subject": "Bert: add the cartoon guide + first appearance on the Get-started panel"
  },
  {
    "sha": "ba35893",
    "subject": "Manage donuts: show a % sign, and return to the modal after the wizard closes"
  },
  {
    "sha": "4ed42bb",
    "subject": "Manage scenario: two completeness donuts (plan + budget) that open each tool"
  },
  {
    "sha": "cb6e7ac",
    "subject": "Plan wizard: tick the \"Your home\" step + seed a homeowner's default home"
  },
  {
    "sha": "af5e095",
    "subject": "Home setup (phase 3): slim the budget's home step to a read-only summary"
  },
  {
    "sha": "bc79387",
    "subject": "Home setup (phase 2): give the family home its own Plan Wizard step"
  },
  {
    "sha": "f0c78d7",
    "subject": "Home setup (phase 1/2): extract a shared HomeEditor component"
  },
  {
    "sha": "8be0542",
    "subject": "Guided setup: fix stale \"completeness ring\" reference on the last step"
  },
  {
    "sha": "8ddb455",
    "subject": "Guided setup: debounce the Monte Carlo so phase-2 sliders stay responsive"
  }
];
