// AUTO-GENERATED by scripts/gen-version.mjs on each build — do not edit by hand.
export const APP_VERSION = "1.0.379";
export const BUILD = 379;
export const GIT_SHA = "31ccc1d";
export const BUILD_DATE = "2026-07-21";
