// Writes lib/version.ts from git at build/dev time. The build number is the git
// commit count — it increments by one on every release (each push → Railway deploy).
// A monotonic guard keeps it from regressing if the build host has a shallow clone.
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "lib", "version.ts");

const git = (cmd) => {
  try {
    return execSync(cmd, { cwd: root, stdio: ["ignore", "pipe", "ignore"] }).toString().trim();
  } catch {
    return "";
  }
};

// Never let a shallow clone (commit count = 1) regress the committed number.
let existing = 0;
try {
  const m = readFileSync(out, "utf8").match(/BUILD\s*=\s*(\d+)/);
  if (m) existing = parseInt(m[1], 10) || 0;
} catch {
  /* first run — no file yet */
}

const count = parseInt(git("git rev-list --count HEAD") || "0", 10) || 0;
const build = Math.max(existing, count);
const sha = git("git rev-parse --short HEAD") || (process.env.RAILWAY_GIT_COMMIT_SHA || "").slice(0, 7) || "dev";
const date = git("git log -1 --format=%cd --date=short") || new Date().toISOString().slice(0, 10);
const version = `1.0.${build}`;

writeFileSync(
  out,
  `// AUTO-GENERATED by scripts/gen-version.mjs on each build — do not edit by hand.
export const APP_VERSION = ${JSON.stringify(version)};
export const BUILD = ${build};
export const GIT_SHA = ${JSON.stringify(sha)};
export const BUILD_DATE = ${JSON.stringify(date)};
`,
);
console.log(`version ${version} (${sha}, ${date})`);
