// Writes lib/version.ts from git at build/dev time. The build number is the git
// commit count — it increments by one on every release (each push → Railway deploy).
// A monotonic guard keeps it from regressing if the build host has a shallow clone.
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "lib", "version.ts");

const git = (cmd) => {
  try {
    return execSync(cmd, { cwd: root, stdio: ["ignore", "pipe", "ignore"] }).toString().trim();
  } catch {
    return "";
  }
};

// Read the previously-committed version.ts so we can PRESERVE fields git can't supply
// on this host. The build host may have no usable git — Railway's Nixpacks ships the
// source WITHOUT .git, which is why `sha` falls back to RAILWAY_GIT_COMMIT_SHA below.
// The committed values (generated locally, where git works) are the fallback.
let prev = "";
try {
  prev = readFileSync(out, "utf8");
} catch {
  /* first run — no file yet */
}
// Never let a shallow/absent clone regress the committed build number.
const existing = parseInt(prev.match(/BUILD\s*=\s*(\d+)/)?.[1] ?? "0", 10) || 0;

const count = parseInt(git("git rev-list --count HEAD") || "0", 10) || 0;
const build = Math.max(existing, count);
const sha = git("git rev-parse --short HEAD") || (process.env.RAILWAY_GIT_COMMIT_SHA || "").slice(0, 7) || "dev";
const date = git("git log -1 --format=%cd --date=short") || new Date().toISOString().slice(0, 10);
const version = `1.0.${build}`;

// Recent commits (short sha + subject), newest-first, no merges — captured HERE at
// build time so the deploy seed step can auto-draft a release from the commits since
// the last release WITHOUT needing git at deploy time. \x1f (unit separator) can't
// appear in a subject, so it's a safe field delimiter. CRITICAL: if this host has no
// git (Railway), KEEP the committed array — otherwise this would wipe it to [] and the
// deploy's release auto-draft would have nothing to work from.
const RECENT = 80;
const logged = git(`git log -n ${RECENT} --no-merges --format=%h%x1f%s`);
let commits;
if (logged) {
  commits = logged
    .split("\n")
    .map((line) => {
      const i = line.indexOf("\x1f");
      return i < 0 ? null : { sha: line.slice(0, i), subject: line.slice(i + 1) };
    })
    .filter(Boolean);
} else {
  const m = prev.match(/export const COMMITS[^=]*=\s*(\[[\s\S]*?\n\]);/);
  try {
    commits = m ? JSON.parse(m[1]) : [];
  } catch {
    commits = [];
  }
}

// On a git-less deploy host (Railway) the preserved COMMITS is missing the very commit
// being deployed — its subject would otherwise never reach the auto-draft. Railway
// exposes the deployed commit via env, so prepend it when it isn't already at the top.
const tipSha = (process.env.RAILWAY_GIT_COMMIT_SHA || "").slice(0, 7);
const tipSubject = (process.env.RAILWAY_GIT_COMMIT_MESSAGE || "").split("\n")[0].trim();
if (tipSha && tipSubject && commits[0]?.sha !== tipSha) {
  commits = [{ sha: tipSha, subject: tipSubject }, ...commits];
}

writeFileSync(
  out,
  `// AUTO-GENERATED by scripts/gen-version.mjs on each build — do not edit by hand.
export const APP_VERSION = ${JSON.stringify(version)};
export const BUILD = ${build};
export const GIT_SHA = ${JSON.stringify(sha)};
export const BUILD_DATE = ${JSON.stringify(date)};
// Newest-first; used by the deploy seed step to auto-draft a release (see autoDraftRelease).
export const COMMITS: { sha: string; subject: string }[] = ${JSON.stringify(commits, null, 2)};
`,
);
console.log(`version ${version} (${sha}, ${date}) — ${commits.length} recent commits captured`);
