// Writes lib/version.ts from git at build/dev time. The build number is the git
// commit count — it increments by one on every release (each push → Railway deploy).
// A monotonic guard keeps it from regressing if the build host has a shallow clone.
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "lib", "version.ts");

const git = (cmd) => {
  try {
    return execSync(cmd, { cwd: root, stdio: ["ignore", "pipe", "ignore"] }).toString().trim();
  } catch {
    return "";
  }
};

// Never let a shallow clone (commit count = 1) regress the committed number.
let existing = 0;
try {
  const m = readFileSync(out, "utf8").match(/BUILD\s*=\s*(\d+)/);
  if (m) existing = parseInt(m[1], 10) || 0;
} catch {
  /* first run — no file yet */
}

const count = parseInt(git("git rev-list --count HEAD") || "0", 10) || 0;
const build = Math.max(existing, count);
const sha = git("git rev-parse --short HEAD") || (process.env.RAILWAY_GIT_COMMIT_SHA || "").slice(0, 7) || "dev";
const date = git("git log -1 --format=%cd --date=short") || new Date().toISOString().slice(0, 10);
const version = `1.0.${build}`;

// Recent commits (short sha + subject), newest-first, no merges — captured HERE at
// build time (git is available) so the deploy seed step can auto-draft a release from
// the commits since the last release WITHOUT needing git at deploy time. \x1f (unit
// separator) can't appear in a subject, so it's a safe field delimiter.
const RECENT = 80;
const commits = git(`git log -n ${RECENT} --no-merges --format=%h%x1f%s`)
  .split("\n")
  .map((line) => {
    const i = line.indexOf("\x1f");
    return i < 0 ? null : { sha: line.slice(0, i), subject: line.slice(i + 1) };
  })
  .filter(Boolean);

writeFileSync(
  out,
  `// AUTO-GENERATED by scripts/gen-version.mjs on each build — do not edit by hand.
export const APP_VERSION = ${JSON.stringify(version)};
export const BUILD = ${build};
export const GIT_SHA = ${JSON.stringify(sha)};
export const BUILD_DATE = ${JSON.stringify(date)};
// Newest-first; used by the deploy seed step to auto-draft a release (see autoDraftRelease).
export const COMMITS: { sha: string; subject: string }[] = ${JSON.stringify(commits, null, 2)};
`,
);
console.log(`version ${version} (${sha}, ${date}) — ${commits.length} recent commits captured`);
